src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @ORM\Table(name="posts")
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable()
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="posts")
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="postCollection")
     */
    private $categoryCollection;

    //Um Post para Varios COmentarios
    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="post")
     * @ORM\OrderBy({"created_at" = "DESC"})
     */
    private $commentsCollection;

    public function __construct()
    {
        $this->categoryCollection = new ArrayCollection();
        $this->commentsCollection = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param ArrayCollection $author
     */
    public function setAuthor(User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategoryCollection()
    {
        return $this->categoryCollection;
    }

    /**
     * @param ArrayCollection $categoryCollection
     */
    public function setCategoryCollection(Category $categoryCollection): self
    {
        if($this->categoryCollection->contains($categoryCollection)){
            return $this;
        }

        $this->categoryCollection[] = $categoryCollection;

        return $this;
    }

    public function getCommentsCollection(){
        return $this->commentsCollection;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @method string getUserIdentifier()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email(message="E-mail inválido")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="Post", mappedBy="author")
     */
    private $posts;

    /**
     * @ORM\Column(type="json")
     */
    private $roles;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getPosts()
    {
        return $this->posts;
    }

    public function __toString()
    {
        return $this->first_name . ' ' . $this->getLastName();
    }

    public function getRoles()
    {
        $roles = explode(', ', $this->roles);
        return $roles;
    }

    public function setRoles($roles)
    {
        $this->roles = 'ROLE_USER';
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function setPassword($password): void
    {
        $this->password = $password;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function __call($name, $arguments)
    {
        // TODO: Implement @method string getUserIdentifier()
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% block stylesheets %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ path('home') }}">Blog SF5</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if app.request.attributes.get('_route') != 'login' %}
                {% for category in categories %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('single_category', {slug: category.slug}) }}">
                            {{ category.name }}
                        </a>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>

{#    {% if is_granted('IS_AUTHENTICATED_FULLY') %}#}
{#        <ul class="navbar-nav float-right">#}
{#            <li class="nav-item">#}
{#                <a href="{{ path('post_index') }}" class="nav-link">Meus Posts</a>#}
{#            </li>#}
{#        </ul>#}
{#    {% endif %}#}
</nav>
<div class="container">
    {% include 'includes/messages.html.twig' %}

    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/base_admin.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% block stylesheets %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ path('home') }}">Blog SF4</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('post_index') }}">Posts</a>
            </li>

            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('user_index') }}">Usuários</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('category_index') }}">Categorias</a>
                </li>
            {% endif %}
        </ul>

    </div>

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <ul class="navbar-nav float-right">
            <li class="nav-item">
                <a href="{{ path('logout') }}" class="nav-link">Sair</a>
            </li>
        </ul>
    {% endif %}
</nav>
<div class="container">
    {% include 'includes/messages.html.twig' %}

    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/category.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        .posts .post p {
            margin-top: 25px;
        }
        .posts .post a {
            text-decoration: none;
            color: #000;
            transition: color .4s ease-in-out;
        }
        .posts .post a:hover {
            color: #999999;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="col-8">
                <div class="row">
                    <h1>Categoria: {{ category.name }}</h1>
                    <hr>
                </div>
                <div class="row posts">
                    {% for post in posts %}
                        <div class="col-12 post">
                            <a href="{{ path('single_post', {slug: post.slug}) }}">
                                <img src="https://placeimg.com/640/280/any" alt="Imagem Post: {{ post.title }}" class="img-fluid">
                                <h2>{{ post.title }}</h2>

                                <small>
                                    Post criado em {{ post.createdAt|date("d/m/Y H:i:s") }}
                                    por {{ post.author.firstName }} | Comentários: {#{ post.commentsCollection.count() }#}
                                </small>

                                <p>
                                    {{ post.description }}
                                </p>
                            </a>
                            <hr>
                        </div>
                    {% endfor %}

                    <!-- Paginator -->
                    <div class="col-12">
                        {{ knp_pagination_render(posts) }}
                    </div>
                </div>
            </div>

            <div class="col-4">

            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
    Blog Symfony 5
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        .posts .post p {
            margin-top: 25px;
        }
        .posts .post a {
            text-decoration: none;
            color: #000;
            transition: color .4s ease-in-out;
        }
        .posts .post a:hover {
            color: #999999;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8">
                <div class="row">
                    <h1 class="">Postagens</h1>
                    <hr>
                </div>

                <div class="row posts">
                    {% for post in posts %}
                        <div class="col-12 post">
                            <a href="{{ path('single_post', {slug: post.slug}) }}">
                                <img src="https://placeimg.com/640/280/any" alt="Imagem Post: {{ post.title }}" class="img-fluid">
                                <h2>{{ post.title }}</h2>

                                <small>
                                    Post criado em {{ post.createdAt|date("d/m/Y H:i:s") }}
                                    por {{ post.author.firstName }} | Comentários: {{ post.commentsCollection.count() }}
                                </small>

                                <p>
                                    {{ post.description }}
                                </p>
                            </a>
                            <hr>
                        </div>
                    {% endfor %}

                    <!-- Paginator -->
                    <div class="col-12">
                        {{ knp_pagination_render(posts) }}
                    </div>
                </div>
            </div>

            <div class="col-4">

            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
    Blog Symfony 5
{% endblock %}

templates/single.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="col-8">
                <div class="row">
                    <div class="col-12">
                        <h2>{{ post.title }}</h2>
                        <small>Post criado em {{ post.createdAt|date("d/m/Y H:i:s") }}
                            por {{ post.author.firstName }} | Comentários: {{ post.commentsCollection.count() }}</small>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ post.content|raw }}
                    </div>
                </div>

                <div class="row">

                   {% if post.commentsCollection.count() %}
                       <div class="col-12">
                           <h3>Comentários</h3>
                           <hr>
                            {% for comment in post.commentsCollection %}
                                <div class="card">
                                    <div class="card-body">
                                        <strong>{{ comment.name }}</strong> - <strong>{{ comment.email }}</strong><br>
                                        <small>Comentado em {{ comment.createdAt|date("d/m/Y H:i:s") }}</small>
                                        <br />
                                        {{ comment.comment }}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <div class="col-12">
                        <hr />
                        <h3>Deixar Comentário</h3>
                        {{ form_start(form, {attr: {action: path('comment_save', {post_id : post.id }), novalidate: 'novalidate'}}) }}
                        {{ form_widget(form) }}
                        <button type="submit" class="btn btn-sm btn-success">Enviar Comentário</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>

            <div class="col-4">

            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
    Blog Symfony 5
{% endblock %}